//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Autonoma.IOT.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Generales {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Generales() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Autonoma.IOT.WebApp.App_GlobalResources.Generales", typeof(Generales).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ACTINCLUSION.
        /// </summary>
        public static string ActivacionCadenas {
            get {
                return ResourceManager.GetString("ActivacionCadenas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ACTIVACIÓN.
        /// </summary>
        public static string ActivacionPospago {
            get {
                return ResourceManager.GetString("ActivacionPospago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ACTIVACIONPRE.
        /// </summary>
        public static string ActivacionPrepago {
            get {
                return ResourceManager.GetString("ActivacionPrepago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo {0} es requerido.
        /// </summary>
        public static string CampoRequerido {
            get {
                return ResourceManager.GetString("CampoRequerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MIGRACIÓN.
        /// </summary>
        public static string Migracion {
            get {
                return ResourceManager.GetString("Migracion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Activación Cadenas.
        /// </summary>
        public static string OptionTramiteCadenas {
            get {
                return ResourceManager.GetString("OptionTramiteCadenas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Migraciones.
        /// </summary>
        public static string OptionTramiteMigracion {
            get {
                return ResourceManager.GetString("OptionTramiteMigracion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Activación Pospago.
        /// </summary>
        public static string OptionTramitePospago {
            get {
                return ResourceManager.GetString("OptionTramitePospago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Activación Prepago.
        /// </summary>
        public static string OptionTramitePrepago {
            get {
                return ResourceManager.GetString("OptionTramitePrepago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo {0} debe estar entre {1} y {2}.
        /// </summary>
        public static string RangoCampo {
            get {
                return ResourceManager.GetString("RangoCampo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rechazada por Datos Incorrectos.
        /// </summary>
        public static string RechazoCadenas {
            get {
                return ResourceManager.GetString("RechazoCadenas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rechazada por Datos Incorrectos.
        /// </summary>
        public static string RechazoPospago {
            get {
                return ResourceManager.GetString("RechazoPospago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rechazada.
        /// </summary>
        public static string RechazoPrepago {
            get {
                return ResourceManager.GetString("RechazoPrepago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a -- Seleccione --.
        /// </summary>
        public static string Seleccione {
            get {
                return ResourceManager.GetString("Seleccione", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Solo se permiten números decimales.
        /// </summary>
        public static string SoloDecimales {
            get {
                return ResourceManager.GetString("SoloDecimales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo {0} debe tener una longitud máxima de {1} caracteres.
        /// </summary>
        public static string TamanioCampo {
            get {
                return ResourceManager.GetString("TamanioCampo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El valor {0} no es válido para {1} .
        /// </summary>
        public static string ValorInvalido {
            get {
                return ResourceManager.GetString("ValorInvalido", resourceCulture);
            }
        }
    }
}
