//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Autonoma.IOT.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LabelCampos {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LabelCampos() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Autonoma.IOT.WebApp.App_GlobalResources.LabelCampos", typeof(LabelCampos).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ACTUALIZACIÓN BDO.
        /// </summary>
        public static string lblACTUALIZACION_BDO {
            get {
                return ResourceManager.GetString("lblACTUALIZACION_BDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a APELLIDO.
        /// </summary>
        public static string lblAPELLIDO {
            get {
                return ResourceManager.GetString("lblAPELLIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Causal.
        /// </summary>
        public static string lblCausal {
            get {
                return ResourceManager.GetString("lblCausal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CENTRO COSTO.
        /// </summary>
        public static string lblCENTRO_COSTO {
            get {
                return ResourceManager.GetString("lblCENTRO_COSTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CFM.
        /// </summary>
        public static string lblCFM {
            get {
                return ResourceManager.GetString("lblCFM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CICLO CORPORATIVO.
        /// </summary>
        public static string lblCICLO_CORPORATIVO {
            get {
                return ResourceManager.GetString("lblCICLO_CORPORATIVO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CIUDAD DEPARTAMENTO.
        /// </summary>
        public static string lblCIUDAD_DEPARTAMENTO {
            get {
                return ResourceManager.GetString("lblCIUDAD_DEPARTAMENTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CO ID.
        /// </summary>
        public static string lblCO_ID {
            get {
                return ResourceManager.GetString("lblCO_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CÓDIGO DISTRIBUIDOR.
        /// </summary>
        public static string lblCODIGO_DISTRIBUIDOR {
            get {
                return ResourceManager.GetString("lblCODIGO_DISTRIBUIDOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CODMIN.
        /// </summary>
        public static string lblCODMIN {
            get {
                return ResourceManager.GetString("lblCODMIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a COMSEGURO.
        /// </summary>
        public static string lblCOMSEGURO {
            get {
                return ResourceManager.GetString("lblCOMSEGURO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CONSECUTIVO.
        /// </summary>
        public static string lblCONSECUTIVO {
            get {
                return ResourceManager.GetString("lblCONSECUTIVO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CUSTOMER ID.
        /// </summary>
        public static string lblCUSTOMER_ID {
            get {
                return ResourceManager.GetString("lblCUSTOMER_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a DATOS.
        /// </summary>
        public static string lblDATOS {
            get {
                return ResourceManager.GetString("lblDATOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a DESTINOS ELEG.
        /// </summary>
        public static string lblDESTINOS_ELEG {
            get {
                return ResourceManager.GetString("lblDESTINOS_ELEG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a DIRECCIÓN.
        /// </summary>
        public static string lblDIRECCION {
            get {
                return ResourceManager.GetString("lblDIRECCION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a DIRECCIÓN EMPRESA.
        /// </summary>
        public static string lblDIRECCION_EMPRESA {
            get {
                return ResourceManager.GetString("lblDIRECCION_EMPRESA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a DISTRIBUIDOR.
        /// </summary>
        public static string lblDISTRIBUIDOR {
            get {
                return ResourceManager.GetString("lblDISTRIBUIDOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a DISTRIBUIDOR MIGRACIÓN.
        /// </summary>
        public static string lblDISTRIBUIDOR_MIGRACION {
            get {
                return ResourceManager.GetString("lblDISTRIBUIDOR_MIGRACION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a DISTRIBUIDOR1.
        /// </summary>
        public static string lblDISTRIBUIDOR1 {
            get {
                return ResourceManager.GetString("lblDISTRIBUIDOR1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a EMPRESA TRABAJO CLIENTE.
        /// </summary>
        public static string lblEMPRESA_TRABAJO_CLIENTE {
            get {
                return ResourceManager.GetString("lblEMPRESA_TRABAJO_CLIENTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a EQUIPO.
        /// </summary>
        public static string lblEQUIPO {
            get {
                return ResourceManager.GetString("lblEQUIPO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ESN.
        /// </summary>
        public static string lblESN {
            get {
                return ResourceManager.GetString("lblESN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ESTADO.
        /// </summary>
        public static string lblESTADO {
            get {
                return ResourceManager.GetString("lblESTADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ESTADOIN.
        /// </summary>
        public static string lblESTADOIN {
            get {
                return ResourceManager.GetString("lblESTADOIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ESTADOMO.
        /// </summary>
        public static string lblESTADOMO {
            get {
                return ResourceManager.GetString("lblESTADOMO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a F PAGO.
        /// </summary>
        public static string lblF_PAGO {
            get {
                return ResourceManager.GetString("lblF_PAGO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a FECBSCS.
        /// </summary>
        public static string lblFECBSCS {
            get {
                return ResourceManager.GetString("lblFECBSCS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a FECHA CORTE.
        /// </summary>
        public static string lblFECHA_CORTE {
            get {
                return ResourceManager.GetString("lblFECHA_CORTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a FECHA INGRESO.
        /// </summary>
        public static string lblFECHA_INGRESO {
            get {
                return ResourceManager.GetString("lblFECHA_INGRESO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a FECHA NACIMIENTO.
        /// </summary>
        public static string lblFECHA_NACIMIENTO {
            get {
                return ResourceManager.GetString("lblFECHA_NACIMIENTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a FECHA PRIMERA CARGA.
        /// </summary>
        public static string lblFECHA_PRIMERA_CARGA {
            get {
                return ResourceManager.GetString("lblFECHA_PRIMERA_CARGA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a FECHA VENTA.
        /// </summary>
        public static string lblFECHA_VENTA {
            get {
                return ResourceManager.GetString("lblFECHA_VENTA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha Final.
        /// </summary>
        public static string lblFechaFinal {
            get {
                return ResourceManager.GetString("lblFechaFinal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha Inicial.
        /// </summary>
        public static string lblFechaInicial {
            get {
                return ResourceManager.GetString("lblFechaInicial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a GENERAR TICKLER.
        /// </summary>
        public static string lblGENERAR_TICKLER {
            get {
                return ResourceManager.GetString("lblGENERAR_TICKLER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a GRUPO CLIENTES.
        /// </summary>
        public static string lblGRUPO_CLIENTES {
            get {
                return ResourceManager.GetString("lblGRUPO_CLIENTES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ICCID.
        /// </summary>
        public static string lblICCID {
            get {
                return ResourceManager.GetString("lblICCID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ID ACTINCLUSIÓN.
        /// </summary>
        public static string lblID_ACTINCLUSION {
            get {
                return ResourceManager.GetString("lblID_ACTINCLUSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ID ACTIVACIÓN.
        /// </summary>
        public static string lblID_ACTIVACION {
            get {
                return ResourceManager.GetString("lblID_ACTIVACION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ID MIGRACIÓN.
        /// </summary>
        public static string lblID_MIGRACION {
            get {
                return ResourceManager.GetString("lblID_MIGRACION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ID VENDEDOR.
        /// </summary>
        public static string lblID_VENDEDOR {
            get {
                return ResourceManager.GetString("lblID_VENDEDOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a IMEI.
        /// </summary>
        public static string lblIMEI {
            get {
                return ResourceManager.GetString("lblIMEI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a IMEIOFQ.
        /// </summary>
        public static string lblIMEIOFQ {
            get {
                return ResourceManager.GetString("lblIMEIOFQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a INDICATIVO.
        /// </summary>
        public static string lblINDICATIVO {
            get {
                return ResourceManager.GetString("lblINDICATIVO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a IVA CFM.
        /// </summary>
        public static string lblIVA_CFM {
            get {
                return ResourceManager.GetString("lblIVA_CFM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a IVA EQUIPO.
        /// </summary>
        public static string lblIVA_EQUIPO {
            get {
                return ResourceManager.GetString("lblIVA_EQUIPO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a IVA SIM.
        /// </summary>
        public static string lblIVA_SIM {
            get {
                return ResourceManager.GetString("lblIVA_SIM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a LINEACT.
        /// </summary>
        public static string lblLINEACT {
            get {
                return ResourceManager.GetString("lblLINEACT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a LINEPORACT.
        /// </summary>
        public static string lblLINEPORACT {
            get {
                return ResourceManager.GetString("lblLINEPORACT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Min:.
        /// </summary>
        public static string lblMin {
            get {
                return ResourceManager.GetString("lblMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MODELO EQUIPO.
        /// </summary>
        public static string lblMODELO_EQUIPO {
            get {
                return ResourceManager.GetString("lblMODELO_EQUIPO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MODELO EQUIPO OFQ.
        /// </summary>
        public static string lblMODELO_EQUIPO_OFQ {
            get {
                return ResourceManager.GetString("lblMODELO_EQUIPO_OFQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MODELO IMEI.
        /// </summary>
        public static string lblMODELO_IMEI {
            get {
                return ResourceManager.GetString("lblMODELO_IMEI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MSISDN.
        /// </summary>
        public static string lblMSISDN {
            get {
                return ResourceManager.GetString("lblMSISDN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a NOMBRE CLIENTE.
        /// </summary>
        public static string lblNOMBRE_CLIENTE {
            get {
                return ResourceManager.GetString("lblNOMBRE_CLIENTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a NOMBRE EQUIPO.
        /// </summary>
        public static string lblNOMBRE_EQUIPO {
            get {
                return ResourceManager.GetString("lblNOMBRE_EQUIPO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a NOMBRES.
        /// </summary>
        public static string lblNOMBRES {
            get {
                return ResourceManager.GetString("lblNOMBRES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Número Documento.
        /// </summary>
        public static string lblNumDocumento {
            get {
                return ResourceManager.GetString("lblNumDocumento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a NÚMERO CONTRATO.
        /// </summary>
        public static string lblNUMERO_CONTRATO {
            get {
                return ResourceManager.GetString("lblNUMERO_CONTRATO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a NÚMERO DOCUMENTO.
        /// </summary>
        public static string lblNUMERO_DOCUMENTO {
            get {
                return ResourceManager.GetString("lblNUMERO_DOCUMENTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a OBSERVACIÓN.
        /// </summary>
        public static string lblOBSERVACION {
            get {
                return ResourceManager.GetString("lblOBSERVACION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a OCC.
        /// </summary>
        public static string lblOCC {
            get {
                return ResourceManager.GetString("lblOCC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a OCUPACIÓN CLIENTE.
        /// </summary>
        public static string lblOCUPACION_CLIENTE {
            get {
                return ResourceManager.GetString("lblOCUPACION_CLIENTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PERMANENCIA.
        /// </summary>
        public static string lblPERMANENCIA {
            get {
                return ResourceManager.GetString("lblPERMANENCIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PLAN TARIFAS.
        /// </summary>
        public static string lblPLAN_TARIFAS {
            get {
                return ResourceManager.GetString("lblPLAN_TARIFAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PLANILLA.
        /// </summary>
        public static string lblPLANILLA {
            get {
                return ResourceManager.GetString("lblPLANILLA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PORCENTAJE ELEG.
        /// </summary>
        public static string lblPORCENTAJE_ELEG {
            get {
                return ResourceManager.GetString("lblPORCENTAJE_ELEG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PRODUCTO.
        /// </summary>
        public static string lblPRODUCTO {
            get {
                return ResourceManager.GetString("lblPRODUCTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a RCAR.
        /// </summary>
        public static string lblRCAR {
            get {
                return ResourceManager.GetString("lblRCAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a RDTC.
        /// </summary>
        public static string lblRDTC {
            get {
                return ResourceManager.GetString("lblRDTC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a RESN.
        /// </summary>
        public static string lblRESN {
            get {
                return ResourceManager.GetString("lblRESN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a RMIN.
        /// </summary>
        public static string lblRMIN {
            get {
                return ResourceManager.GetString("lblRMIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a RTAR.
        /// </summary>
        public static string lblRTAR {
            get {
                return ResourceManager.GetString("lblRTAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SALUDO.
        /// </summary>
        public static string lblSALUDO {
            get {
                return ResourceManager.GetString("lblSALUDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SCCODE.
        /// </summary>
        public static string lblSCCODE {
            get {
                return ResourceManager.GetString("lblSCCODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SEXO.
        /// </summary>
        public static string lblSEXO {
            get {
                return ResourceManager.GetString("lblSEXO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SPCODE.
        /// </summary>
        public static string lblSPCODE {
            get {
                return ResourceManager.GetString("lblSPCODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SPCODE PAQ.
        /// </summary>
        public static string lblSPCODE_PAQ {
            get {
                return ResourceManager.GetString("lblSPCODE_PAQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a TECNOLOGÍA.
        /// </summary>
        public static string lblTECNOLOGIA {
            get {
                return ResourceManager.GetString("lblTECNOLOGIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a TELÉFONO.
        /// </summary>
        public static string lblTELEFONO {
            get {
                return ResourceManager.GetString("lblTELEFONO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a TELÉFONO EMPRESA.
        /// </summary>
        public static string lblTELEFONO_EMPRESA {
            get {
                return ResourceManager.GetString("lblTELEFONO_EMPRESA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a TIPO CONTRATO.
        /// </summary>
        public static string lblTIPO_CONTRATO {
            get {
                return ResourceManager.GetString("lblTIPO_CONTRATO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a TIPO DOCUMENTO.
        /// </summary>
        public static string lblTIPO_DOCUMENTO {
            get {
                return ResourceManager.GetString("lblTIPO_DOCUMENTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo Documento.
        /// </summary>
        public static string lblTipoDocumento {
            get {
                return ResourceManager.GetString("lblTipoDocumento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a TMCODE.
        /// </summary>
        public static string lblTMCODE {
            get {
                return ResourceManager.GetString("lblTMCODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a TOTAL VENTA.
        /// </summary>
        public static string lblTOTAL_VENTA {
            get {
                return ResourceManager.GetString("lblTOTAL_VENTA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a TRAJO EQUIPO.
        /// </summary>
        public static string lblTRAJO_EQUIPO {
            get {
                return ResourceManager.GetString("lblTRAJO_EQUIPO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a TRAJO ICCID.
        /// </summary>
        public static string lblTRAJO_ICCID {
            get {
                return ResourceManager.GetString("lblTRAJO_ICCID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Trámite.
        /// </summary>
        public static string lblTramite {
            get {
                return ResourceManager.GetString("lblTramite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a USUARIO.
        /// </summary>
        public static string lblUSUARIO {
            get {
                return ResourceManager.GetString("lblUSUARIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a VALOR CFM.
        /// </summary>
        public static string lblVALOR_CFM {
            get {
                return ResourceManager.GetString("lblVALOR_CFM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a VALOR EQUIPO ESPECIAL.
        /// </summary>
        public static string lblVALOR_EQUIPO_ESPECIAL {
            get {
                return ResourceManager.GetString("lblVALOR_EQUIPO_ESPECIAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a VALOR ICCID ESPECIAL.
        /// </summary>
        public static string lblVALOR_ICCID_ESPECIAL {
            get {
                return ResourceManager.GetString("lblVALOR_ICCID_ESPECIAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a VALOR IVA EQUIPO ESPECIAL.
        /// </summary>
        public static string lblVALOR_IVA_EQUIPO_ESPECIAL {
            get {
                return ResourceManager.GetString("lblVALOR_IVA_EQUIPO_ESPECIAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a VALOR IVA ICCID ESPECIAL.
        /// </summary>
        public static string lblVALOR_IVA_ICCID_ESPECIAL {
            get {
                return ResourceManager.GetString("lblVALOR_IVA_ICCID_ESPECIAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a VALOR PAGAR.
        /// </summary>
        public static string lblVALOR_PAGAR {
            get {
                return ResourceManager.GetString("lblVALOR_PAGAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a VALOR PAGARSIM.
        /// </summary>
        public static string lblVALOR_PAGARSIM {
            get {
                return ResourceManager.GetString("lblVALOR_PAGARSIM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a VLR EQUIPO.
        /// </summary>
        public static string lblVLR_EQUIPO {
            get {
                return ResourceManager.GetString("lblVLR_EQUIPO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a VLR SIM.
        /// </summary>
        public static string lblVLR_SIM {
            get {
                return ResourceManager.GetString("lblVLR_SIM", resourceCulture);
            }
        }
    }
}
